FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# 기본 명령은 웹 서버(gunicorn)로
CMD ["sh", "-c", "python manage.py migrate && gunicorn board_project.wsgi:application --bind 0.0.0.0:8000"]
